// <auto-generated />
namespace yourTrip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NameEmailID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameEmailID));
        
        string IMigrationMetadata.Id
        {
            get { return "201801201758166_NameEmailID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
